const ACTION_TYPES = {
	COMMON: {
		GO_BACK: 'GO_BACK',
		ENTER_CATEGORY: 'ENTER_CATEGORY',
		CREATE_CATEGORY: 'CREATE_CATEGORY',
		CREATE_ITEM: 'CREATE_ITEM',
		ON_REMOVE: 'ON_REMOVE',
	},
};

export default ACTION_TYPES;
